"""start of code

Revision ID: 860a9d4529a7
Revises: 
Create Date: 2023-09-25 20:43:17.214996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860a9d4529a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committees',
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('committee_name', sa.String(length=255), nullable=True),
    sa.Column('committee_members', sa.Text(), nullable=True),
    sa.Column('topics_covered', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('committee_id')
    )
    op.create_table('constitutional_conventions',
    sa.Column('convention_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('convention_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('document_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('debates',
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('debate_date', sa.Date(), nullable=True),
    sa.Column('debate_location', sa.String(length=255), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('debate_content', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.committee_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('debate_id')
    )
    op.create_table('commentaries',
    sa.Column('commentary_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('commentary_text', sa.Text(), nullable=True),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.debate_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('commentary_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaries')
    op.drop_table('debates')
    op.drop_table('documents')
    op.drop_table('constitutional_conventions')
    op.drop_table('committees')
    # ### end Alembic commands ###
